<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWtecb1y\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWtecb1y/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWtecb1y.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerWtecb1y\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerWtecb1y\appProdProjectContainer(array(
    'container.build_hash' => 'Wtecb1y',
    'container.build_id' => '2bfc23b1',
    'container.build_time' => 1543310979,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWtecb1y');
